#ifndef BOX_SCALE_TOOL_SIDE_H
#define BOX_SCALE_TOOL_SIDE_H
enum{
    BOX_SCALE_TOOL_SIDE_LEFT, 
    BOX_SCALE_TOOL_SIDE_RIGHT,
    BOX_SCALE_TOOL_SIDE_BOTTOM,
    BOX_SCALE_TOOL_SIDE_TOP,
    BOX_SCALE_TOOL_SIDE_FRONT,
    BOX_SCALE_TOOL_SIDE_BACK,
    BOX_SCALE_TOOL_SIDE_COUNT
};
#endif