#ifndef ELEMENT_BUFFER_ID_H
#define ELEMENT_BUFFER_ID_H
enum element_buffer_id{ELEMENT_BUFFER_ID_RAY_HIT, 
    ELEMENT_BUFFER_SELECTION_BOX,
    ELEMENT_BUFFER_X_MOVE_PULLEY,
    ELEMENT_BUFFER_Y_MOVE_PULLEY,
    ELEMENT_BUFFER_Z_MOVE_PULLEY,

    ELEMENT_BUFFER_NX_BOX_SCALE_PULLEY,
    ELEMENT_BUFFER_PX_BOX_SCALE_PULLEY,
    ELEMENT_BUFFER_NY_BOX_SCALE_PULLEY,
    ELEMENT_BUFFER_PY_BOX_SCALE_PULLEY,
    ELEMENT_BUFFER_NZ_BOX_SCALE_PULLEY,
    ELEMENT_BUFFER_PZ_BOX_SCALE_PULLEY,


    ELEMENT_BUFFER_ID_COUNT};
#endif