#ifndef RAY_HIT_ENTITY_H
#define RAY_HIT_ENTITY_H
enum ray_hit_entity{
    RAY_HIT_ENTITY_NONE, 
    RAY_HIT_ENTITY_Y0, 
    RAY_HIT_ENTITY_X_MOVE_PULLEY, 
    RAY_HIT_ENTITY_Y_MOVE_PULLEY,
    RAY_HIT_ENTITY_Z_MOVE_PULLEY,
    RAY_HIT_ENTITY_VOXEL_MODEL
};
#endif