#ifndef SELECTION_TOOL_STATE_H
#define SELECTION_TOOL_STATE_H
enum selection_tool_state{
    SELECTION_TOOL_STATE_PICK_ORIGIN,
    SELECTION_TOOL_STATE_PICK_AREA,
    SELECTION_TOOL_STATE_CONFIRMED,
    SELECTION_TOOL_STATE_VOXEL_SELECTED,
    SELECTION_TOOL_STATE_VOXEL_CONFIRMED
};
#endif