#ifndef TOOL_ID_H
#define TOOL_ID_H
enum tool_id{
    TOOL_ID_NO_TOOL, 
    TOOL_ID_VOXEL_MANIPULATOR,
    TOOL_ID_SELECTION_TOOL, 
    TOOL_ID_BOX_SCALE_TOOL,
    TOOL_ID_MOVE_TOOL, 
    TOOL_ID_FLIP_TOOL,
    TOOL_ID_ADD_TOOL,
    TOOL_ID_REMOVE_TOOL,


};
#endif