#ifndef VOXEL_EDITOR_SHAPE_ID_H
#define VOXEL_EDITOR_SHAPE_ID_H
enum voxel_editor_shape_id{VOXEL_EDITOR_SHAPE_ID_POINT, VOXEL_EDITOR_SHAPE_ID_CUBE, 
    VOXEL_EDITOR_SHAPE_ID_SPHERE, VOXEL_EDITOR_SHAPE_ID_COUNT};
#endif